// D&D reference data for the player character sheet.
// Ported from the user's existing React character-builder component —
// same content, restructured as a plain global object (window.DND) so it can
// be used from vanilla JS without a build step.
window.DND = (function(){

  const SKILLS = [
    { name: 'Acrobatics',      ability: 'dex' },
    { name: 'Animal Handling', ability: 'wis' },
    { name: 'Arcana',          ability: 'int' },
    { name: 'Athletics',       ability: 'str' },
    { name: 'Deception',       ability: 'cha' },
    { name: 'History',         ability: 'int' },
    { name: 'Insight',         ability: 'wis' },
    { name: 'Intimidation',    ability: 'cha' },
    { name: 'Investigation',   ability: 'int' },
    { name: 'Medicine',        ability: 'wis' },
    { name: 'Nature',          ability: 'int' },
    { name: 'Perception',      ability: 'wis' },
    { name: 'Performance',     ability: 'cha' },
    { name: 'Persuasion',      ability: 'cha' },
    { name: 'Religion',        ability: 'int' },
    { name: 'Sleight of Hand', ability: 'dex' },
    { name: 'Stealth',         ability: 'dex' },
    { name: 'Survival',        ability: 'wis' },
  ];

  const ABILITIES = ['str','dex','con','int','wis','cha'];
  const ABILITY_LABELS = {
    str:'Strength', dex:'Dexterity', con:'Constitution',
    int:'Intelligence', wis:'Wisdom', cha:'Charisma',
  };

  const SUBCLASSES = {
    'Barbarian': ['Path of the Berserker','Path of the Totem Warrior','Path of the Ancestral Guardian','Path of the Storm Herald','Path of the Zealot','Path of the Beast','Path of Wild Magic'],
    'Bard':      ['College of Lore','College of Valor','College of Glamour','College of Swords','College of Whispers','College of Creation','College of Eloquence','College of Spirits'],
    'Cleric':    ['Knowledge Domain','Life Domain','Light Domain','Nature Domain','Tempest Domain','Trickery Domain','War Domain','Arcana Domain','Death Domain','Forge Domain','Grave Domain','Order Domain','Peace Domain','Twilight Domain'],
    'Druid':     ['Circle of the Land','Circle of the Moon','Circle of Dreams','Circle of the Shepherd','Circle of Spores','Circle of Stars','Circle of Wildfire'],
    'Fighter':   ['Battle Master','Champion','Eldritch Knight','Arcane Archer','Cavalier','Samurai','Psi Warrior','Rune Knight'],
    'Monk':      ['Way of the Open Hand','Way of Shadow','Way of the Four Elements','Way of the Drunken Master','Way of the Kensei','Way of the Sun Soul','Way of Mercy','Way of the Astral Self'],
    'Paladin':   ['Oath of Devotion','Oath of the Ancients','Oath of Vengeance','Oath of Conquest','Oath of Redemption','Oath of Glory','Oath of the Watchers','Oathbreaker'],
    'Ranger':    ['Hunter','Beast Master','Gloom Stalker','Horizon Walker','Monster Slayer','Fey Wanderer','Swarmkeeper'],
    'Rogue':     ['Thief','Assassin','Arcane Trickster','Inquisitive','Mastermind','Scout','Swashbuckler','Phantom','Soulknife'],
    'Sorcerer':  ['Draconic Bloodline','Wild Magic','Divine Soul','Shadow Magic','Storm Sorcery','Aberrant Mind','Clockwork Soul'],
    'Warlock':   ['The Archfey','The Fiend','The Great Old One','The Hexblade','The Celestial','The Undying','The Fathomless','The Genie'],
    'Wizard':    ['School of Abjuration','School of Conjuration','School of Divination','School of Enchantment','School of Evocation','School of Illusion','School of Necromancy','School of Transmutation','Bladesinger','War Magic','Chronurgy Magic','Graviturgy Magic'],
  };

  const CLASS_HIT_DIE = {
    Barbarian: 12, Fighter: 10, Paladin: 10, Ranger: 10,
    Bard: 8, Cleric: 8, Druid: 8, Monk: 8, Rogue: 8, Warlock: 8,
    Sorcerer: 6, Wizard: 6,
  };

  const CLASS_RESOURCE = {
    Barbarian: { label: 'Rage',           max: (l) => l >= 20 ? 999 : l >= 17 ? 6 : l >= 12 ? 5 : l >= 6 ? 4 : l >= 3 ? 3 : 2, resetsOn: 'long' },
    Monk:      { label: 'Ki points',      max: (l) => l,                                                                     resetsOn: 'short' },
    Sorcerer:  { label: 'Sorcery points', max: (l) => l >= 2 ? l : 0,                                                        resetsOn: 'long' },
  };

  const SPELLCASTING_ABILITY = {
    Bard:'cha', Cleric:'wis', Druid:'wis', Paladin:'cha', Ranger:'wis', Sorcerer:'cha', Warlock:'cha', Wizard:'int',
  };

  const CANTRIPS_KNOWN = {
    Bard:     [2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4],
    Cleric:   [3,3,3,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5],
    Druid:    [2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4],
    Sorcerer: [4,4,4,5,5,5,5,5,5,6,6,6,6,6,6,6,6,6,6,6],
    Warlock:  [2,2,2,3,3,3,3,3,3,4,4,4,4,4,4,4,4,4,4,4],
    Wizard:   [3,3,3,4,4,4,4,4,4,5,5,5,5,5,5,5,5,5,5,5],
  };

  const SPELLS_KNOWN = {
    Bard:     [4,5,6,7,8,9,10,11,12,14,14,15,15,16,18,19,19,20,22,22],
    Sorcerer: [2,3,4,5,6,7,8,9,10,11,12,12,13,13,14,14,15,15,15,15],
    Warlock:  [2,3,4,5,6,7,8,9,10,10,11,11,12,12,13,13,14,14,15,15],
    Ranger:   [0,2,3,3,4,4,5,6,6,7,7,8,9,9,10,10,11,11,11,11],
  };
  const KNOWN_CASTERS = new Set(Object.keys(SPELLS_KNOWN));

  const SPELL_SLOTS = {
    1:[2,0,0,0,0,0,0,0,0], 2:[3,0,0,0,0,0,0,0,0], 3:[4,2,0,0,0,0,0,0,0],
    4:[4,3,0,0,0,0,0,0,0], 5:[4,3,2,0,0,0,0,0,0], 6:[4,3,3,0,0,0,0,0,0],
    7:[4,3,3,1,0,0,0,0,0], 8:[4,3,3,2,0,0,0,0,0], 9:[4,3,3,3,1,0,0,0,0],
    10:[4,3,3,3,2,0,0,0,0],11:[4,3,3,3,2,1,0,0,0],12:[4,3,3,3,2,1,0,0,0],
    13:[4,3,3,3,2,1,1,0,0],14:[4,3,3,3,2,1,1,0,0],15:[4,3,3,3,2,1,1,1,0],
    16:[4,3,3,3,2,1,1,1,0],17:[4,3,3,3,2,1,1,1,1],18:[4,3,3,3,3,1,1,1,1],
    19:[4,3,3,3,3,2,1,1,1],20:[4,3,3,3,3,2,2,1,1],
  };

  const NON_CASTERS = new Set(['Barbarian','Fighter','Monk','Rogue']);
  const HALF_CASTERS = new Set(['Paladin','Ranger']);

  const CLASS_SAVE_PROFS = {
    Barbarian:['str','con'], Bard:['dex','cha'], Cleric:['wis','cha'],
    Druid:['int','wis'], Fighter:['str','con'], Monk:['str','dex'],
    Paladin:['wis','cha'], Ranger:['str','dex'], Rogue:['dex','int'],
    Sorcerer:['con','cha'], Warlock:['wis','cha'], Wizard:['int','wis'],
  };

  const CLASS_FEATURES = {
    Barbarian: [
      [1,'Rage','Bonus action. While raging: +2 damage (Str attacks), resistance to B/P/S damage. Ends if no attack/damage taken or you end it. Uses: 2 (scales with level).'],
      [1,'Unarmored Defense','AC = 10 + Dex mod + Con mod when not wearing armor.'],
      [2,'Reckless Attack','First attack with advantage. Attacks against you also have advantage until next turn.'],
      [2,'Danger Sense','Advantage on Dex saves against visible effects (traps, spells).'],
      [3,'Primal Path','Choose your subclass.'],
      [4,'ASI','Ability Score Improvement: +2 to one score or +1 to two scores.'],
      [5,'Extra Attack','Attack twice when you take the Attack action.'],
      [5,'Fast Movement','+10 ft speed when not wearing heavy armor.'],
      [7,'Feral Instinct','Advantage on initiative rolls. Can act normally when surprised if you enter rage.'],
      [9,'Brutal Critical','Roll one additional weapon damage die on a critical hit.'],
      [11,'Relentless Rage','If you drop to 0 HP while raging, make Con save (DC 10, +5 each use) to stay at 1 HP.'],
      [15,'Persistent Rage','Rage only ends early if you fall unconscious or choose to end it.'],
      [20,'Primal Champion','+4 Strength, +4 Constitution (max 24).'],
    ],
    Bard: [
      [1,'Spellcasting','Cha-based. You know 2 cantrips + 4 spells at L1; more as you level.'],
      [1,'Bardic Inspiration','Bonus action: a creature within 60 ft gains a Bardic Inspiration die (d6→d12). Add to one attack, ability check, or save within 10 min. Uses = Cha mod/long rest.'],
      [2,'Jack of All Trades','Add half your proficiency bonus (round down) to ability checks you lack proficiency in.'],
      [2,'Song of Rest','Allies who hear you during a short rest regain extra HP: d6 (L2), d8 (L9), d10 (L13), d12 (L17).'],
      [3,'Expertise','Double proficiency on 2 skills of your choice.'],
      [3,'Bard College','Choose your subclass.'],
      [4,'ASI','Ability Score Improvement.'],
      [5,'Font of Inspiration','Regain all Bardic Inspiration uses on a short rest.'],
      [6,'Countercharm','Action: until start of next turn, you and allies within 30 ft have advantage vs. frightened/charmed.'],
      [10,'Magical Secrets','Learn 2 spells from any class. Repeat at L14 and L18.'],
      [20,'Superior Inspiration','Regain 1 Bardic Inspiration when you roll initiative with none remaining.'],
    ],
    Cleric: [
      [1,'Spellcasting','Wis-based. Prepare Wis mod + cleric level spells each long rest.'],
      [1,'Divine Domain','Choose your subclass (domain). Grants domain spells and features.'],
      [2,'Channel Divinity','Use once per short rest. Turn Undead or use domain ability.'],
      [4,'ASI','Ability Score Improvement.'],
      [5,'Destroy Undead','Undead that fail Turn Undead save are destroyed if CR ≤ threshold (scales with level).'],
      [10,'Divine Intervention','Call on your deity. Roll d100; succeeds on ≤ cleric level. Recharges on long rest.'],
      [20,'Divine Intervention','Automatically succeeds. Recharges on long rest.'],
    ],
    Druid: [
      [1,'Druidic','You know Druidic, a secret druid language.'],
      [1,'Spellcasting','Wis-based. Prepare Wis mod + druid level spells each long rest.'],
      [2,'Wild Shape','Bonus action: transform into a beast (CR limits apply). 2 uses/short rest.'],
      [2,'Druid Circle','Choose your subclass.'],
      [4,'ASI','Ability Score Improvement.'],
      [10,'Beast Spells','Maintain concentration and perform verbal/somatic spell components while in Wild Shape.'],
      [18,'Timeless Body','Age 10× slower than normal. Immune to magical aging.'],
      [20,'Archdruid','Unlimited Wild Shape uses.'],
    ],
    Fighter: [
      [1,'Fighting Style','Choose: Archery (+2 ranged atk), Defense (+1 AC in armor), Dueling (+2 dmg one-handed), Great Weapon (reroll 1s/2s), Protection (impose disadv on adjacent attack), Two-Weapon (+ability mod to offhand).'],
      [1,'Second Wind','Bonus action: regain 1d10 + fighter level HP. Recharges on short rest.'],
      [2,'Action Surge','Take one additional action on your turn. Recharges on short rest (2 uses at L17).'],
      [3,'Martial Archetype','Choose your subclass.'],
      [4,'ASI','Ability Score Improvement.'],
      [5,'Extra Attack','Attack twice when you take the Attack action.'],
      [9,'Indomitable','Reroll a failed saving throw (must use new roll). 1/long rest; 2 at L13, 3 at L17.'],
      [11,'Extra Attack (2)','Attack three times when you take the Attack action.'],
      [20,'Extra Attack (3)','Attack four times when you take the Attack action.'],
    ],
    Monk: [
      [1,'Unarmored Defense','AC = 10 + Dex mod + Wis mod when not wearing armor or shield.'],
      [1,'Martial Arts','Use Dex for unarmed/monk weapon attacks. Unarmed die: d4 (L1), d6 (L5), d8 (L11), d10 (L17). Bonus action unarmed strike after Attack action.'],
      [2,'Ki','Ki points = monk level. Flurry of Blows (2 ki: 2 bonus unarmed strikes), Patient Defense (1 ki: Dodge), Step of the Wind (1 ki: Disengage or Dash + doubled jump).'],
      [2,'Unarmored Movement','+10 ft speed (scales: +15 at L6, +20 at L10, +25 at L14, +30 at L18).'],
      [3,'Monastic Tradition','Choose your subclass.'],
      [3,'Deflect Missiles','Reaction: reduce ranged weapon damage by 1d10 + Dex + monk level. If reduced to 0, catch and throw back (1 ki).'],
      [4,'Slow Fall','Reaction: reduce fall damage by 5 × monk level.'],
      [5,'Extra Attack','Attack twice when you take the Attack action.'],
      [5,'Stunning Strike','1 ki after hitting: target makes Con save or is stunned until end of your next turn.'],
      [6,'Ki-Empowered Strikes','Unarmed strikes count as magical for overcoming resistance.'],
      [7,'Evasion','No damage on successful Dex save (for half damage effects); half damage on fail.'],
      [14,'Diamond Soul','Proficiency in all saving throws. Spend 1 ki to reroll a failed save.'],
      [20,'Perfect Self','Regain 4 ki on initiative roll if you have 0 remaining.'],
    ],
    Paladin: [
      [1,'Divine Sense','Detect celestials, fiends, undead within 60 ft as an action. Uses = 1 + Cha mod/long rest.'],
      [1,'Lay on Hands','Pool of HP = paladin level × 5. Touch to restore HP, or spend 5 to cure disease/poison.'],
      [2,'Fighting Style','Choose: Defense, Dueling, Great Weapon, or Protection.'],
      [2,'Spellcasting','Cha-based. Prepare Cha mod + half paladin level (round down) spells.'],
      [2,'Divine Smite','When you hit a melee attack, expend a spell slot: 2d8 radiant (+1d8/slot level above 1st, max 5d8). +1d8 vs undead/fiends.'],
      [3,'Sacred Oath','Choose your subclass.'],
      [5,'Extra Attack','Attack twice when you take the Attack action.'],
      [6,'Aura of Protection','You and allies within 10 ft add Cha mod to saving throws (min +1). 20 ft at L18.'],
      [7,'Aura of Courage','You and allies within 10 ft can\'t be frightened. 20 ft at L18.'],
      [11,'Improved Divine Smite','All melee weapon attacks deal +1d8 radiant damage.'],
      [20,'Sacred Oath Capstone','Powerful oath-specific transformation (see subclass).'],
    ],
    Ranger: [
      [1,'Favored Enemy','Advantage on Survival to track and Int to recall info about chosen enemy type.'],
      [1,'Natural Explorer','Double proficiency on Int/Wis checks for chosen terrain type. Various travel benefits.'],
      [2,'Fighting Style','Choose: Archery, Defense, Dueling, or Two-Weapon.'],
      [2,'Spellcasting','Wis-based. Prepare Wis mod + half ranger level (round down) spells.'],
      [3,'Ranger Archetype','Choose your subclass.'],
      [3,'Primeval Awareness','Spend a spell slot: sense aberrations/celestials/dragons/elementals/fey/fiends/undead within 1 mile (6 miles in favored terrain) for 1 min/slot level.'],
      [5,'Extra Attack','Attack twice when you take the Attack action.'],
      [8,'Land\'s Stride','Nonmagical difficult terrain costs no extra movement. Advantage on saves vs. magical plants.'],
      [14,'Vanish','Use Hide as a bonus action. Can\'t be tracked by nonmagical means (leave no tracks).'],
      [20,'Foe Slayer','Once per turn, add Wis mod to attack or damage roll against a favored enemy.'],
    ],
    Rogue: [
      [1,'Expertise','Double proficiency on 2 skills (or 1 skill + Thieves\' Tools).'],
      [1,'Sneak Attack','+1d6 damage when you have advantage or an ally is adjacent to target (no disadvantage). Scales: +1d6 every 2 levels.'],
      [1,'Thieves\' Cant','Secret language/code used by criminals and rogues.'],
      [2,'Cunning Action','Bonus action: Dash, Disengage, or Hide.'],
      [3,'Roguish Archetype','Choose your subclass.'],
      [4,'ASI','Ability Score Improvement.'],
      [5,'Uncanny Dodge','Reaction: halve the damage from one attack you can see.'],
      [7,'Evasion','No damage on successful Dex save; half damage on fail.'],
      [11,'Reliable Talent','Minimum roll of 10 on any ability check you\'re proficient in.'],
      [15,'Slippery Mind','Gain proficiency in Wisdom saving throws.'],
      [18,'Elusive','Attackers never have advantage on attack rolls against you.'],
      [20,'Stroke of Luck','If you miss an attack or fail an ability check, treat it as a hit/20. Recharges on short rest.'],
    ],
    Sorcerer: [
      [1,'Spellcasting','Cha-based. You know a set number of spells (4 at L1, scaling up).'],
      [1,'Sorcerous Origin','Choose your subclass.'],
      [2,'Font of Magic','Sorcery points = sorcerer level. Flexible Casting: convert points ↔ spell slots.'],
      [3,'Metamagic','Choose 2 options (more at L10, L17): Careful, Distant, Empowered, Extended, Heightened, Quickened, Seeking, Subtle, Twinned.'],
      [4,'ASI','Ability Score Improvement.'],
      [20,'Sorcerous Restoration','Regain 4 sorcery points on a short rest.'],
    ],
    Warlock: [
      [1,'Otherworldly Patron','Choose your subclass (patron).'],
      [1,'Pact Magic','Cha-based. Spell slots recharge on short rest. All slots are at your highest available level.'],
      [2,'Eldritch Invocations','Choose 2 invocations from the list; gain more as you level.'],
      [3,'Pact Boon','Choose Pact of the Blade (weapon), Chain (familiar), or Tome (book of spells).'],
      [4,'ASI','Ability Score Improvement.'],
      [11,'Mystic Arcanum','Cast one 6th-level spell once per long rest without a slot (7th at L13, 8th at L15, 9th at L17).'],
      [20,'Eldritch Master','Spend 1 minute entreating your patron to regain all Pact Magic slots. 1/long rest.'],
    ],
    Wizard: [
      [1,'Spellcasting','Int-based. Spellbook starts with 6 spells; add 2 per level. Prepare Int mod + wizard level spells.'],
      [1,'Arcane Recovery','Short rest: recover spell slots totaling ≤ half wizard level (rounded up, max 5th level). 1/day.'],
      [2,'Arcane Tradition','Choose your subclass (school of magic).'],
      [4,'ASI','Ability Score Improvement.'],
      [18,'Spell Mastery','Choose one 1st-level and one 2nd-level spell; cast each at their lowest level without expending a slot.'],
      [20,'Signature Spells','Choose two 3rd-level spells; cast each once without a slot per short rest.'],
    ],
  };

  const RACE_TRAITS = {
    'Astral Elf':      '+2/+1 to ability scores of choice. Speed 30 ft. Darkvision 60 ft. Immune to magical sleep. Advantage vs. charmed. Sacred Flame cantrip (at-will). Misty Step (at level 5, 1/long rest). Vampiric Gaze: Charm Person 1/short rest. Vampire\'s Bite: deal+regain temp HP (Prof uses/long rest).',
    'Dark Elf (Drow)': '+2 Dex, +1 Cha. Speed 30 ft. Darkvision 120 ft. Sunlight Sensitivity. Immune to magical sleep. Advantage vs. charmed. Perception proficiency. Drow Magic: Dancing Lights (cantrip), Faerie Fire 1/long rest (L3), Darkness 1/long rest (L5).',
    'Dragonborn':      '+2 Str, +1 Cha. Speed 30 ft. Choose a draconic ancestry type (determines breath weapon damage type and saving throw). Breath Weapon: 2d6 damage in a 15 ft cone or 30 ft line, Con save for half. Damage Resistance matching your ancestry.',
    'Dwarf (Hill)':    '+2 Con, +1 Wis. Speed 25 ft (not reduced by heavy armor). Darkvision 60 ft. Dwarven Resilience: advantage on saves vs. poison, resistance to poison. Weapon proficiency: battleaxe, handaxe, warhammer, light hammer. Stonecunning: double proficiency on History checks for stonework. Tool proficiency of choice.',
    'Dwarf (Mountain)':'+2 Str, +2 Con. Speed 25 ft. Darkvision 60 ft. Same poison resistance as Hill Dwarf. Light + medium armor proficiency. Weapon proficiency: battleaxe, handaxe, warhammer, light hammer. Stonecunning.',
    'Elf (High)':      '+2 Dex, +1 Int. Speed 30 ft. Darkvision 60 ft. Immune to magical sleep. Advantage vs. charmed. Perception proficiency. Trance (4 hr long rest). One wizard cantrip (Int-based). Proficiency: longsword, shortsword, longbow, shortbow. One extra language.',
    'Fairy':           '+2/+1 to ability scores of choice. Speed 30 ft, Fly 30 ft. Darkvision 60 ft. Fairy Magic: Druidcraft cantrip (at-will). Faerie Fire and Enlarge/Reduce 1/long rest each (Int/Wis/Cha spellcasting).',
    'Gnome (Forest)':  '+1 Dex, +2 Int. Speed 25 ft. Darkvision 60 ft. Gnome Cunning: advantage on Int/Wis/Cha saves vs. magic. Natural Illusionist: Minor Illusion cantrip (Int). Speak with Small Beasts.',
    'Gnome (Rock)':    '+1 Con, +2 Int. Speed 25 ft. Darkvision 60 ft. Gnome Cunning. Artificer\'s Lore: double proficiency on magic item History checks. Tinker: create tiny clockwork devices.',
    'Half-Elf':        '+2 Cha, +1 to two other ability scores. Speed 30 ft. Darkvision 60 ft. Fey Ancestry: advantage vs. charmed, immune to magical sleep. Two skill proficiencies of your choice.',
    'Half-Orc':        '+2 Str, +1 Con. Speed 30 ft. Darkvision 60 ft. Intimidation proficiency. Relentless Endurance: when reduced to 0 HP, drop to 1 HP instead (1/long rest). Savage Attacks: roll one extra damage die on melee critical hits.',
    'Halfling (Lightfoot)': '+2 Dex, +1 Cha. Speed 25 ft. Lucky: reroll 1s on attack rolls, ability checks, saving throws. Brave: advantage vs. frightened. Nimbleness: move through the space of larger creatures. Naturally Stealthy: hide behind creatures at least one size larger.',
    'Halfling (Stout)': '+2 Dex, +1 Con. Speed 25 ft. Lucky. Brave. Nimbleness. Stout Resilience: advantage vs. poison, resistance to poison.',
    'Human':           '+1 to all six ability scores. Speed 30 ft. One extra language of your choice.',
    'Human (Variant)': '+1 to two ability scores of your choice. Speed 30 ft. One skill proficiency of your choice. One feat of your choice. One extra language.',
    'Tiefling':        '+1 Int, +2 Cha. Speed 30 ft. Darkvision 60 ft. Hellish Resistance: fire resistance. Infernal Legacy: Thaumaturgy cantrip; Hellish Rebuke (L3, 1/long rest); Darkness (L5, 1/long rest). Cha spellcasting.',
    'Wood Elf':        '+2 Dex, +1 Wis. Speed 35 ft. Darkvision 60 ft. Immune to magical sleep. Advantage vs. charmed. Perception proficiency. Trance. Proficiency: longsword, shortsword, longbow, shortbow. Mask of the Wild: hide when lightly obscured by natural phenomena.',
    'Custom Lineage':  '+2 to one ability score of your choice. Small or Medium size. One feat of your choice. Either darkvision 60 ft OR proficiency in one skill. One extra language.',
  };

  const FEATS = [
    { name:'Alert',          desc:'+5 initiative. Can\'t be surprised. Hidden creatures don\'t gain advantage on attacks vs. you.', asi: null },
    { name:'Actor',          desc:'+1 Charisma (max 20). Advantage on Deception/Performance when impersonating. Mimic voices.', asi: { amount: 1, choose: ['cha'] } },
    { name:'Athlete',        desc:'+1 Str or Dex. Stand up uses only 5 ft movement. Climb at full speed. Running jump with 5 ft run-up.', asi: { amount: 1, choose: ['str', 'dex'] } },
    { name:'Charger',        desc:'After Dash, bonus attack (+5 damage) or shove 10 ft.', asi: null },
    { name:'Crossbow Expert',desc:'Ignore loading. No disadvantage in melee. Bonus hand crossbow attack after Attack action.', asi: null },
    { name:'Defensive Duelist', desc:'Req: Dex 13. Reaction with finesse weapon: add proficiency bonus to AC against one attack.', asi: null },
    { name:'Dual Wielder',   desc:'+1 AC. Two-weapon fight with non-light weapons. Draw two weapons at once.', asi: null },
    { name:'Dungeon Delver', desc:'Advantage on Perception/Investigation for secret doors. Advantage on trap saves. Resistance to trap damage.', asi: null },
    { name:'Durable',        desc:'+1 Constitution (max 20). Min roll on Hit Dice = twice Con mod.', asi: { amount: 1, choose: ['con'] } },
    { name:'Elemental Adept',desc:'Req: spellcasting. Choose damage type; spells ignore resistance, treat 1s as 2s on damage dice.', asi: null },
    { name:'Fey Touched',    desc:'+1 Int, Wis, or Cha. Learn Misty Step + one 1st-level divination or enchantment spell. Cast each free 1/long rest.', asi: { amount: 1, choose: ['int', 'wis', 'cha'] } },
    { name:'Great Weapon Master', desc:'Critical or kill → bonus attack. Option: −5 attack for +10 damage.', asi: null },
    { name:'Healer',         desc:'Healer\'s Kit: stabilize (target wakes at 1 HP). Heal 1d6+4+HD HP once per target per rest.', asi: null },
    { name:'Heavy Armor Master', desc:'Req: heavy armor prof. +1 Strength. B/P/S damage reduced by 3 while in heavy armor.', asi: null },
    { name:'Inspiring Leader', desc:'Req: Cha 13. 10-min speech: up to 6 allies gain temp HP = level + Cha mod.', asi: null },
    { name:'Lucky',          desc:'3 luck points/long rest. Spend to roll extra d20 on attack/check/save or give enemy disadvantage.', asi: null },
    { name:'Mage Slayer',    desc:'Reaction: attack spellcaster after they cast in melee. Advantage on saves vs. adjacent spellcasters. Concentration disadvantage after your attacks.', asi: null },
    { name:'Magic Initiate', desc:'Choose a class: learn 2 cantrips + one 1st-level spell (1/long rest free).', asi: null },
    { name:'Metamagic Adept',desc:'Req: spellcasting. Learn 2 Metamagic options. Gain 2 sorcery points.', asi: null },
    { name:'Mobile',         desc:'+10 ft speed. Dash ignores difficult terrain. No opportunity attack from creatures you attack (hit or miss).', asi: null },
    { name:'Observant',      desc:'+1 Int or Wis. +5 passive Perception and Investigation. Lip reading.', asi: { amount: 1, choose: ['int', 'wis'] } },
    { name:'Polearm Master', desc:'Bonus attack with butt end (1d4). Opportunity attack when creature enters your reach.', asi: null },
    { name:'Resilient',      desc:'Choose ability score: +1 (max 20), proficiency in that saving throw.', asi: { amount: 1, choose: ABILITIES } },
    { name:'Sentinel',       desc:'Opportunity attack reduces speed to 0. No Disengage from opportunity attacks. Reaction attack when adjacent creature attacks someone else.', asi: null },
    { name:'Shadow Touched', desc:'+1 Int, Wis, or Cha. Learn Invisibility + one 1st-level illusion or necromancy spell. Cast each free 1/long rest.', asi: { amount: 1, choose: ['int', 'wis', 'cha'] } },
    { name:'Sharpshooter',   desc:'No disadvantage at long range. Ignore half/three-quarters cover. Option: −5 attack for +10 damage.', asi: null },
    { name:'Shield Master',  desc:'Bonus shove after Attack. Add shield bonus to Dex saves targeting only you. No damage on successful Dex save.', asi: null },
    { name:'Silvery Barbs',  desc:'Req: Bard/Sorcerer/Wizard. Reaction: force reroll, take lower result; give another creature advantage on next roll.', asi: null },
    { name:'Skilled',        desc:'Proficiency in any 3 skills or tools.', asi: null },
    { name:'Telekinetic',    desc:'+1 Int, Wis, or Cha. Mage Hand (invisible). Bonus action: push/pull creature 5 ft.', asi: { amount: 1, choose: ['int', 'wis', 'cha'] } },
    { name:'Telepathic',     desc:'+1 Int, Wis, or Cha. Telepathic speech within 60 ft. Detect Thoughts 1/long rest free.', asi: { amount: 1, choose: ['int', 'wis', 'cha'] } },
    { name:'Tough',          desc:'HP max increases by 2 per level (retroactive).', asi: null },
    { name:'War Caster',     desc:'Req: spellcasting. Advantage on concentration saves. Somatic components with full hands. Opportunity attack can be a spell.', asi: null },
    { name:'Weapon Master',  desc:'+1 Str or Dex. Proficiency with 4 weapons of your choice.', asi: { amount: 1, choose: ['str', 'dex'] } },
  ];

  const BACKGROUNDS = {
    'Acolyte': {
      skills: ['Insight','Religion'], tools: 'None', languages: 'Two of your choice',
      equipment: 'Holy symbol, prayer book or prayer wheel, 5 sticks of incense, vestments, common clothes, 15 gp',
      feature: 'Shelter of the Faithful',
      featureDesc: 'You and your companions can receive free healing and care at temples of your faith. You have ties to a specific temple and can call on the priests there for assistance.',
      trait: 'I idolize a hero of my faith.', ideal: 'Tradition. The ancient traditions must be preserved.',
      bond: 'I will someday get revenge on the corrupt temple hierarchy.', flaw: 'I am inflexible in my thinking.',
    },
    'Charlatan': {
      skills: ['Deception','Sleight of Hand'], tools: 'Disguise kit, forgery kit', languages: 'None',
      equipment: 'Fine clothes, disguise kit, tools of the con of your choice, 15 gp',
      feature: 'False Identity',
      featureDesc: 'You have created a second identity including documentation, established acquaintances, and disguises. You can also forge documents as long as you have seen similar ones.',
      trait: 'I fall in and out of love easily.', ideal: 'Independence. I am a free spirit — no one tells me what to do.',
      bond: 'I fleeced the wrong person and must work to repay my debt.', flaw: 'I can\'t resist a pretty face.',
    },
    'Criminal': {
      skills: ['Deception','Stealth'], tools: 'One type of gaming set, thieves\' tools', languages: 'None',
      equipment: 'Crowbar, dark common clothes with a hood, 15 gp',
      feature: 'Criminal Contact',
      featureDesc: 'You have a reliable and trustworthy contact who acts as your liaison to a network of other criminals. You know how to get messages to and from your contact.',
      trait: 'I always have a plan for when things go wrong.', ideal: 'Freedom. Chains are meant to be broken.',
      bond: 'I\'m trying to pay off an old debt I owe to a generous benefactor.', flaw: 'When I see something valuable, I can\'t think about anything but how to steal it.',
    },
    'Entertainer': {
      skills: ['Acrobatics','Performance'], tools: 'Disguise kit, one type of musical instrument', languages: 'None',
      equipment: 'Musical instrument, favor of admirer, costume, 15 gp',
      feature: 'By Popular Demand',
      featureDesc: 'You can always find a place to perform, and receive free lodging and food of modest quality. Your performance makes you something of a local figure.',
      trait: 'I know a story relevant to almost every situation.', ideal: 'Creativity. The world needs new ideas and bold action.',
      bond: 'I want to be famous, whatever it takes.', flaw: 'I have trouble keeping my true feelings hidden.',
    },
    'Folk Hero': {
      skills: ['Animal Handling','Survival'], tools: 'One type of artisan\'s tools, vehicles (land)', languages: 'None',
      equipment: 'Artisan\'s tools, shovel, iron pot, common clothes, 10 gp',
      feature: 'Rustic Hospitality',
      featureDesc: 'Since you come from the common folk, you fit in among them with ease. You can find a place to hide, rest, or recuperate among commoners, unless you\'ve shown yourself to be a danger to them.',
      trait: 'I judge people by their actions, not their words.', ideal: 'Respect. People deserve to be treated with dignity.',
      bond: 'I protect those who cannot protect themselves.', flaw: 'I\'m convinced of the significance of my destiny and blind to my shortcomings.',
    },
    'Guild Artisan': {
      skills: ['Insight','Persuasion'], tools: 'One type of artisan\'s tools', languages: 'One of your choice',
      equipment: 'Artisan\'s tools, letter of introduction from guild, traveler\'s clothes, 15 gp',
      feature: 'Guild Membership',
      featureDesc: 'You have the support of your guild. Fellow members provide lodging and food, and can help you find work. In an emergency, the guild may provide legal assistance.',
      trait: 'I believe that anything worth doing is worth doing right.', ideal: 'Community. It is the duty of all to strengthen the bonds of community.',
      bond: 'The workshop where I apprenticed belongs to my family.', flaw: 'I\'ll do anything to get my hands on something rare or priceless.',
    },
    'Hermit': {
      skills: ['Medicine','Religion'], tools: 'Herbalism kit', languages: 'One of your choice',
      equipment: 'Scroll case with notes, winter blanket, common clothes, herbalism kit, 5 gp',
      feature: 'Discovery',
      featureDesc: 'The quiet seclusion of your extended hermitage gave you access to a unique and powerful discovery — a secret of nature, the multiverse, the gods, or the forces that drive them.',
      trait: 'I\'ve been isolated for so long that I rarely speak, preferring gestures and expressions.', ideal: 'Greater Good. My gifts are meant to be shared with all.',
      bond: 'I entered seclusion to hide from those who might still be hunting me.', flaw: 'I like keeping secrets and won\'t share them with anyone.',
    },
    'Noble': {
      skills: ['History','Persuasion'], tools: 'One type of gaming set', languages: 'One of your choice',
      equipment: 'Fine clothes, signet ring, scroll of pedigree, purse with 25 gp',
      feature: 'Position of Privilege',
      featureDesc: 'Thanks to your noble birth, people are inclined to think the best of you. You are welcome in high society, and common folk make every effort to accommodate you.',
      trait: 'My favor, once lost, is lost forever.', ideal: 'Responsibility. It is my duty to respect the authority of those above me.',
      bond: 'I will face any challenge to win the approval of my family.', flaw: 'I secretly believe that everyone is beneath me.',
    },
    'Outlander': {
      skills: ['Athletics','Survival'], tools: 'One type of musical instrument', languages: 'One of your choice',
      equipment: 'Staff, hunting trap, trophy from an animal, traveler\'s clothes, 10 gp',
      feature: 'Wanderer',
      featureDesc: 'You have an excellent memory for maps and geography, and can always recall the general layout of terrain. You can find food and fresh water for yourself and up to 5 others each day.',
      trait: 'I watch over my friends as if they were a litter of newborn pups.', ideal: 'Change. Life is like the seasons — in constant change.',
      bond: 'My family, clan, or tribe is the most important thing in my life.', flaw: 'I am slow to trust members of other races.',
    },
    'Sage': {
      skills: ['Arcana','History'], tools: 'None', languages: 'Two of your choice',
      equipment: 'Bottle of ink, quill, small knife, letter from dead colleague, common clothes, 10 gp',
      feature: 'Researcher',
      featureDesc: 'When you attempt to learn or recall a piece of lore, if you don\'t know the information, you often know where and from whom you can obtain it.',
      trait: 'I use polysyllabic words that convey the impression of great erudition.', ideal: 'Knowledge. The path to power and self-improvement is through knowledge.',
      bond: 'I have an ancient text that holds secrets that must not fall into the wrong hands.', flaw: 'I am easily distracted by the promise of information.',
    },
    'Sailor': {
      skills: ['Athletics','Perception'], tools: 'Navigator\'s tools, vehicles (water)', languages: 'None',
      equipment: 'Belaying pin (club), 50 ft silk rope, lucky charm, common clothes, 10 gp',
      feature: 'Ship\'s Passage',
      featureDesc: 'When you need to, you can secure free passage on a sailing ship for yourself and companions in exchange for working during the voyage.',
      trait: 'My friends know they can rely on me, no matter what.', ideal: 'Respect. The thing that keeps a ship together is respect for the captain.',
      bond: 'I\'ll always remember my first ship.', flaw: 'Once someone questions my courage, I never back down.',
    },
    'Soldier': {
      skills: ['Athletics','Intimidation'], tools: 'One type of gaming set, vehicles (land)', languages: 'None',
      equipment: 'Insignia of rank, trophy from fallen enemy, gaming set, common clothes, 10 gp',
      feature: 'Military Rank',
      featureDesc: 'You have a military rank. Soldiers loyal to your former military organization still recognize your authority, and they will defer to you if they are of a lower rank.',
      trait: 'I can stare down a hell hound without flinching.', ideal: 'Greater Good. Our lot is to lay down our lives in defense of others.',
      bond: 'I fight for those who cannot fight for themselves.', flaw: 'I have little respect for those who are not a proven warrior.',
    },
    'Urchin': {
      skills: ['Sleight of Hand','Stealth'], tools: 'Disguise kit, thieves\' tools', languages: 'None',
      equipment: 'Small knife, map of home city, pet mouse, token from parents, common clothes, 10 gp',
      feature: 'City Secrets',
      featureDesc: 'You know the secret patterns and flows to cities and can find passages through the urban sprawl that others would miss. You can travel twice the normal speed.',
      trait: 'I hide scraps of food and trinkets away in my pockets.', ideal: 'Community. We have to take care of each other.',
      bond: 'I owe a debt I can never repay to the person who took pity on me.', flaw: 'It\'s not stealing if I need it more than someone else.',
    },
    'City Watch': {
      skills: ['Athletics','Insight'], tools: 'None', languages: 'Two of your choice',
      equipment: 'Uniform of your organization, horn, manacles, 10 gp',
      feature: 'Watcher\'s Eye',
      featureDesc: 'Your experience in enforcing the law lets you identify local law enforcement quickly. You can find the local watch, guards, or officers in any settlement.',
      trait: 'I\'m always polite and respectful.', ideal: 'Nation. My city, nation, or people are all that matter.',
      bond: 'I worked hard to achieve my position and I\'ll defend it.', flaw: 'I have a weakness for the vices of the city.',
    },
    'Clan Crafter': {
      skills: ['History','Insight'], tools: 'One type of artisan\'s tools', languages: 'Dwarvish or one other',
      equipment: 'Artisan\'s tools, maker\'s mark chisel, traveler\'s clothes, 15 gp',
      feature: 'Respect of the Stout Folk',
      featureDesc: 'You always have free lodging and food available in any community with dwarves, as long as you have not shown yourself to be a danger to them.',
      trait: 'I take my time when crafting — quality over speed.', ideal: 'Tradition. Clan traditions must be preserved and upheld.',
      bond: 'My tools are sacred to me; I would rather die than part with them.', flaw: 'I\'m horribly jealous of anyone with better tools.',
    },
    'Cloistered Scholar': {
      skills: ['History', 'One from Arcana, Nature, or Religion'], tools: 'None', languages: 'Two of your choice',
      equipment: 'Reference book, writing kit, borrowed book, common clothes, 10 gp',
      feature: 'Library Access',
      featureDesc: 'You have free access to most libraries and can obtain assistance from the scholars there. You know how to navigate academic bureaucracy.',
      trait: 'I\'ve read so many books that I can quote them in any situation.', ideal: 'Knowledge. Learning is its own reward.',
      bond: 'My life\'s work is a series of tomes related to my field.', flaw: 'I am dismissive of those who aren\'t as educated as I am.',
    },
    'Courtier': {
      skills: ['Insight','Persuasion'], tools: 'None', languages: 'Two of your choice',
      equipment: 'Fine clothes, 5 gp',
      feature: 'Court Functionary',
      featureDesc: 'Your knowledge of how bureaucracies function lets you gain access to the records and inner workings of any noble court.',
      trait: 'I believe everyone has a hidden agenda and I constantly look for it.', ideal: 'Community. I strive to ensure that everyone benefits from my actions.',
      bond: 'I hope to serve a great leader.', flaw: 'I have an insatiable desire for carnal pleasures.',
    },
    'Far Traveler': {
      skills: ['Insight','Perception'], tools: 'One musical instrument or gaming set from your homeland', languages: 'One of your choice',
      equipment: 'Traveler\'s clothes, trinket from homeland, 15 gp',
      feature: 'All Eyes on You',
      featureDesc: 'Your accent, mannerisms, and clothing all mark you as foreign. Curious folk will show interest in you and help you in exchange for news of distant lands.',
      trait: 'I have different assumptions about personal space and boundaries.', ideal: 'Open. I have much to learn from the kindly folk I meet.',
      bond: 'I am homesick and long for the familiar sights of my homeland.', flaw: 'I have a weakness for the exotic, even if it causes me trouble.',
    },
    'Haunted One': {
      skills: ['Choose two from Arcana, Investigation, Religion, or Survival'], tools: 'None',
      languages: 'One exotic language (Abyssal, Celestial, Deep Speech, Draconic, Infernal, Primordial, Sylvan, or Undercommon)',
      equipment: 'Monster hunter\'s pack, dark common clothes, 1 sp',
      feature: 'Heart of Darkness',
      featureDesc: 'Those who look into your eyes can see that you have faced unimaginable horror and survived. Common folk make way for you; they sense the darkness in you.',
      trait: 'I don\'t talk about the thing that torments me.', ideal: 'I try to help those in need, no matter what the personal cost.',
      bond: 'I keep my monstrous nature a secret as best I can.', flaw: 'I have certain phobias rooted in my harrowing experience.',
    },
    'Inheritor': {
      skills: ['Survival', 'One from Arcana, History, or Religion'], tools: 'Your choice of a gaming set or a musical instrument', languages: 'None',
      equipment: 'Inheritance item, traveler\'s clothes, any gear related to your inheritance, 15 gp',
      feature: 'Inheritance',
      featureDesc: 'You inherit something of great value — a document, a weapon, a piece of jewelry — that carries a great responsibility or secret.',
      trait: 'I have a strong sense of fairness and always try to find the most equitable solution.', ideal: 'Responsibility. I must care for what has been entrusted to me.',
      bond: 'My inheritance is the most important thing in my life.', flaw: 'I am oblivious to the obvious.',
    },
    'Knight of the Order': {
      skills: ['Persuasion', 'One from Arcana, History, Nature, or Religion'], tools: 'One type of gaming set or musical instrument', languages: 'One of your choice',
      equipment: 'Traveler\'s clothes, signet of your order, 10 gp',
      feature: 'Knightly Regard',
      featureDesc: 'You receive shelter and succor from members of your knightly order and those who are sympathetic to its aims.',
      trait: 'I\'m still trying to live up to the example set by my order\'s founder.', ideal: 'Responsibility. I do what I must and accept the consequences.',
      bond: 'I\'ll never forget the crushing defeat my order suffered, or the enemies who dealt it.', flaw: 'I\'m too quick to assume that solutions involve violence.',
    },
    'Mercenary Veteran': {
      skills: ['Athletics','Persuasion'], tools: 'One type of gaming set, vehicles (land)', languages: 'None',
      equipment: 'Uniform of your company, insignia of your rank, gaming set, 10 gp',
      feature: 'Mercenary Life',
      featureDesc: 'You know the mercenary life as only someone who has lived it can. You are able to identify mercenary companies and know their reputations.',
      trait: 'I\'m used to hard work and am slow to quit.', ideal: 'Coin. I\'m only in it for the money.',
      bond: 'My honor is my life.', flaw: 'I have a gambling problem.',
    },
    'Urban Bounty Hunter': {
      skills: ['Choose two from Deception, Insight, Persuasion, or Stealth'], tools: 'Two from thieves\' tools, disguise kit, or one gaming set', languages: 'None',
      equipment: 'A set of clothes appropriate to your duties and a pouch containing 20 gp',
      feature: 'Ear to the Ground',
      featureDesc: 'You are in frequent contact with people in the segment of society that your chosen quarries move through. You can gather information about their whereabouts.',
      trait: 'I always have a plan for when things go wrong.', ideal: 'Greater Good. I help people who help themselves.',
      bond: 'I have a client who means a great deal to me.', flaw: 'I have a weakness for a certain vice.',
    },
    'Uthgardt Tribe Member': {
      skills: ['Athletics','Survival'], tools: 'One type of musical instrument or artisan\'s tools', languages: 'One of your choice',
      equipment: 'Hunting trap, totemic token, traveler\'s clothes, 10 gp',
      feature: 'Uthgardt Heritage',
      featureDesc: 'You have excellent knowledge of your tribe\'s territory and can find twice the normal amount of food when foraging. You are also familiar with the sacred sites of your tribe.',
      trait: 'I\'m driven by a wanderlust that led me away from home.', ideal: 'Change. The world is in need of new ideas and bold action.',
      bond: 'My tribe is the most important thing in my life.', flaw: 'I follow orders even if I think they\'re wrong.',
    },
    'Waterdhavian Noble': {
      skills: ['History','Persuasion'], tools: 'One type of gaming set or musical instrument', languages: 'One of your choice',
      equipment: 'Fine clothes, signet ring, scroll of pedigree, skin of fine zzar, 20 gp',
      feature: 'Kept in Style',
      featureDesc: 'While in Waterdeep or elsewhere, if in a city of similar size, you can maintain a comfortable lifestyle for free, as your family\'s name smooths the way.',
      trait: 'I take great pains to always look my best.', ideal: 'Responsibility. It is my duty to respect the authority of those above me.',
      bond: 'My house\'s alliance with another noble family must be sustained.', flaw: 'I hide a truly scandalous secret.',
    },
  };

  const CLASS_SKILL_CHOICES = {
    Barbarian: { count: 2, options: ['Animal Handling','Athletics','Intimidation','Nature','Perception','Survival'] },
    Bard:      { count: 3, options: ['Acrobatics','Animal Handling','Arcana','Athletics','Deception','History','Insight','Intimidation','Investigation','Medicine','Nature','Perception','Performance','Persuasion','Religion','Sleight of Hand','Stealth','Survival'] },
    Cleric:    { count: 2, options: ['History','Insight','Medicine','Persuasion','Religion'] },
    Druid:     { count: 2, options: ['Arcana','Animal Handling','Insight','Medicine','Nature','Perception','Religion','Survival'] },
    Fighter:   { count: 2, options: ['Acrobatics','Animal Handling','Athletics','History','Insight','Intimidation','Perception','Survival'] },
    Monk:      { count: 2, options: ['Acrobatics','Athletics','History','Insight','Religion','Stealth'] },
    Paladin:   { count: 2, options: ['Athletics','Insight','Intimidation','Medicine','Persuasion','Religion'] },
    Ranger:    { count: 3, options: ['Animal Handling','Athletics','Insight','Investigation','Nature','Perception','Stealth','Survival'] },
    Rogue:     { count: 4, options: ['Acrobatics','Athletics','Deception','Insight','Intimidation','Investigation','Perception','Performance','Persuasion','Sleight of Hand','Stealth'] },
    Sorcerer:  { count: 2, options: ['Arcana','Deception','Insight','Intimidation','Persuasion','Religion'] },
    Warlock:   { count: 2, options: ['Arcana','Deception','History','Intimidation','Investigation','Nature','Religion'] },
    Wizard:    { count: 2, options: ['Arcana','History','Insight','Investigation','Medicine','Religion'] },
  };

  return {
    SKILLS, ABILITIES, ABILITY_LABELS, SUBCLASSES, CLASS_HIT_DIE, CLASS_RESOURCE,
    SPELLCASTING_ABILITY, CANTRIPS_KNOWN, SPELLS_KNOWN, SPELL_SLOTS,
    NON_CASTERS, HALF_CASTERS, KNOWN_CASTERS, CLASS_SAVE_PROFS,
    CLASS_FEATURES, RACE_TRAITS, FEATS, BACKGROUNDS, CLASS_SKILL_CHOICES,
  };
})();